[project]
name = "electronica-digital"
version = "0.1.0"
description = "Documentacion de elctronica digital basica"
authors = [
    {name = "Josef Leyva",email = "jalm_x@hotmail.com"}
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mkdocs-material (>=9.7.7,<10.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
